# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-09 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crea_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AddField(
            model_name='categoria',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crea_post.Post'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_level',
            field=models.CharField(choices=[('1', 'level 1'), ('2', 'level 2'), ('3', 'level 3')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crea_post.Categoria'),
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='photos',
            field=models.ManyToManyField(null=True, related_name='subcategoryphoto', to='crea_post.Photo'),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crea_post.Countries'),
        ),
    ]
