# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crea_post', '0003_subcategoria_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crea_post.Post'),
        ),
    ]
