# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crea_post', '0004_auto_20170710_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='country',
        ),
        migrations.AddField(
            model_name='countries',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crea_post.Post'),
        ),
    ]
