# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crea_post', '0005_auto_20170712_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crea_post.Countries'),
        ),
    ]
