# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crea_post', '0006_categoria_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_level',
        ),
        migrations.AddField(
            model_name='categoria',
            name='has_sub_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='countries',
            name='has_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.ImageField(null=True, upload_to='posts/%Y'),
        ),
    ]
