# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crea_post', '0007_auto_20170712_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='photos',
        ),
    ]
