# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crea_post', '0008_auto_20170712_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='countries',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crea_post.Categoria'),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crea_post.Countries'),
        ),
        migrations.AddField(
            model_name='post',
            name='sub_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crea_post.SubCategoria'),
        ),
    ]
