# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20170711_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='parentsubcategory',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='post_level',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='parent_sub_category',
        ),
        migrations.AddField(
            model_name='category',
            name='has_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gallery',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.SubCategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.Category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='has_category',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ParentSubCategory',
        ),
        migrations.AddField(
            model_name='childsubcategory',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.SubCategory'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='child_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='album.ChildSubCategory'),
        ),
    ]
